language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  artifacts:
    s3_region: $ARTIFACTS_S3_REGION
    paths:
      - ./web/sites/simpletest
      - ./web/sites/default/files

services:
  - docker

php:
  - 7.2

env:
  global:
    - DRUPAL_BASE_URL="http://127.0.0.1:8080"
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - TRAVIS_NODE_VERSION="4"
  matrix:
    - JOB=job:check-coding-standards
    - JOB=job:run-unit-tests
    - JOB="job:run-kernel-tests widgets-1,widgets-2,widgets-3"
    - JOB="job:run-kernel-tests widgets-4,publications-1,publications-2,wysiwyg,vsite,os,os-theme-preview"
    - JOB="job:run-kernel-tests cp,other,cp-menu,profiles,redirect,cp-appearance"
    - JOB="job:run-functional-tests classes,events,pages,cp,media-browser,os-theme-preview,breadcrumbs,cp-menu,vsite_favicon"
    - JOB="job:run-functional-tests analytics,publications,cp-appearance,redirect,twitter,os,vsite"
    - JOB="job:run-functional-javascript-tests classes,pages,publications,cp-appearance,cp-menu,profiles,cp,mailchimp,metatag,redirect"
    - JOB="job:run-functional-javascript-tests events,os,vsite,os-theme-preview,widgets,blog,faq,news,presentations"
#    - JOB=job:run-behat-tests

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer global require consolidation/robo

before_script:
  - cp .travis/RoboFile.php .

script:
  - robo $JOB

after_failure:
  - artifacts upload

after_success:
  - bash <(curl -s https://codecov.io/bash)
