bibcite_revision_delete.settings:
  type: config_object
  label: 'Publication Revision Delete settings'
  mapping:
    bibcite_revision_delete_cron:
      type: integer
      label: 'Number of revisions to remove in each cron run'
    bibcite_revision_delete_time:
      type: integer
      label: 'Frequency with which to delete revisions while cron is running'
    bibcite_revision_minimum_revisions_to_keep:
      type: integer
      label: 'The number of minimum version to keep'
